function createfigure(X1, Y1, Z1, X2, Y2, Z2, X3, Z3)
%CREATEFIGURE(X1, Y1, Z1, X2, Y2, Z2, X3, Z3)
%  X1:  vector of plot3 x data
%  Y1:  vector of plot3 y data
%  Z1:  vector of plot3 z data
%  X2:  vector of plot3 x data
%  Y2:  vector of plot3 y data
%  Z2:  vector of plot3 z data
%  X3:  vector of plot3 x data
%  Z3:  vector of plot3 z data

%  Auto-generated by MATLAB on 01-Jan-2023 12:43:48

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot3
plot3(X1,Y1,Z1,'DisplayName','UAV Trajectory','MarkerSize',8,'Marker','o',...
    'LineWidth',2,...
    'LineStyle','-.',...
    'Color',[0 0 0]);

% Create plot3
plot3(X2,Y2,Z2,'DisplayName','Estimated Target Location',...
    'MarkerIndices',[1 6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96 101 106 111 116],...
    'MarkerSize',8,...
    'Marker','x',...
    'LineWidth',2,...
    'LineStyle',':',...
    'Color',[0 0 1]);

% Create plot3
plot3(X3,X3,Z3,'DisplayName','Target Location','MarkerEdgeColor',[1 0 0],...
    'MarkerSize',10,...
    'Marker','pentagram',...
    'LineStyle','none');

% Create zlabel
zlabel('Heights');

% Create ylabel
ylabel('Y-axis (m)');

% Create xlabel
xlabel('X-axis (m)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-10 350]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 350]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 4]);
view(axes1,[422.679007737332 26.5355152002293]);
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',18,'FontWeight','bold','GridAlpha',0.3,...
    'MinorGridLineStyle','-');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.468032347639162 0.744047619047619 0.439285714285713 0.154761904761905]);

