function plot_style(XMatrix1, Y1)
%CREATEFIGURE(XMatrix1, Y1)
%  XMATRIX1:  matrix of plot x data
%  Y1:  vector of plot y data

%  Auto-generated by MATLAB on 05-Dec-2022 17:26:20

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(XMatrix1,Y1,'LineWidth',3,'Parent',axes1);
set(plot1(1),'DisplayName','Parallel - LLS','Color',[0 0 1]);
set(plot1(2),'DisplayName','Squre - LLS','LineStyle','--','Color',[0 0 1]);
set(plot1(3),'DisplayName','Parallel - NLS','Color',[1 0 0]);
set(plot1(4),'DisplayName','Squre - NLS','LineStyle','--','Color',[1 0 0]);

% Create ylabel
ylabel('CDF','FontWeight','bold','FontName','Helvetica Neue');

% Create xlabel
xlabel('Error Distance(m)','FontWeight','bold','FontName','Helvetica Neue');

box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontName','Helvetica Neue','FontSize',14,'FontWeight','bold',...
    'GridAlpha',1,'MinorGridAlpha',0.5);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.608928571428571 0.116666666666669 0.292857142857143 0.241666666666667],...
    'FontSize',20,...
    'FontWeight','normal');

